spring:
  application:
    name: netdrops

logging:
  level:
    root: WARN
    org.example.netdrops: WARN

server:
  tomcat:
    threads:
      max: 800
      min-spare: 50
    max-connections: 20000
    accept-count: 500

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
